name: Auto-update fpm Formula

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  update-fpm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch latest fpm release
        id: get-latest-release
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/fortran-lang/fpm/releases/latest | jq -r '.tag_name')
          echo "Latest version: $LATEST_VERSION"
          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV

      - name: Extract current formula version
        id: get-current-version
        run: |
          CURRENT_VERSION=$(grep -oP 'url "https://github.com/fortran-lang/fpm/releases/download/v\K[0-9.]+(?=/fpm-)' Formula/fpm.rb)
          echo "Current version: $CURRENT_VERSION"
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV

      - name: Compare versions
        id: check-update
        run: |
          if [ "$LATEST_VERSION" != "$CURRENT_VERSION" ]; then
            echo "New version available!"
            echo "UPDATE_NEEDED=true" >> $GITHUB_ENV
          else
            echo "No update needed."
          fi

      - name: Get new SHA256 hash
        if: env.UPDATE_NEEDED == 'true'
        id: get-sha256
        run: |
          SHA_URL="https://github.com/fortran-lang/fpm/releases/download/${LATEST_VERSION}/fpm-${LATEST_VERSION}.zip.sha256"
          SHA256=$(curl -sL $SHA_URL | awk '{print $1}')
          echo "New SHA256: $SHA256"
          echo "SHA256=$SHA256" >> $GITHUB_ENV

      - name: Update formula
        if: env.UPDATE_NEEDED == 'true'
        run: |
          sed -i "s|url \".*\"|url \"https://github.com/fortran-lang/fpm/releases/download/${LATEST_VERSION}/fpm-${LATEST_VERSION}.zip\"|" Formula/fpm.rb
          sed -i "s|sha256 \".*\"|sha256 \"${SHA256}\"|" Formula/fpm.rb

      - name: Commit and push changes
        if: env.UPDATE_NEEDED == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add Formula/fpm.rb
          git commit -m "Update fpm to ${LATEST_VERSION}"
          git push

